export const COUNTRIES = [
  { name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE', dialCode: '+971' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dialCode: '+966' },
  { name: 'Qatar', flag: '🇶🇦', code: 'QA', dialCode: '+974' },
  { name: 'Bahrain', flag: '🇧🇭', code: 'BH', dialCode: '+973' },
  { name: 'Kuwait', flag: '🇰🇼', code: 'KW', dialCode: '+965' },
  { name: 'Oman', flag: '🇴🇲', code: 'OM', dialCode: '+968' },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dialCode: '+44' },
  { name: 'United States', flag: '🇺🇸', code: 'US', dialCode: '+1' },
  { name: 'Singapore', flag: '🇸🇬', code: 'SG', dialCode: '+65' },
  { name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dialCode: '+852' },
  { name: 'Ireland', flag: '🇮🇪', code: 'IE', dialCode: '+353' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE', dialCode: '+49' },
  { name: 'France', flag: '🇫🇷', code: 'FR', dialCode: '+33' },
  { name: 'Netherlands', flag: '🇳🇱', code: 'NL', dialCode: '+31' },
  { name: 'Canada', flag: '🇨🇦', code: 'CA', dialCode: '+1' },
  { name: 'Australia', flag: '🇦🇺', code: 'AU', dialCode: '+61' },
  { name: 'India', flag: '🇮🇳', code: 'IN', dialCode: '+91' },
]